### ISSUE TITLE
Issue in the hwt.c code

### ISSUE THREAD

**Issue by vikas-srivastava-1729** [hmchoe0528/SMAUG-T_public#4]
This is regarding the code for ternary vector sampler https://github.com/hmchoe0528/SMAUG-T_public/blob/main/reference_implementation/src/hwt.c
In line 33,
     `   div++;`

What is the reason for incrementing ` div ` by 1?

I tried to write a C-code to check the modulo bias using the method mentioned in the hwt.c file but I observed that biasness at the last index.

```
#include <stdio.h>
#include <stdint.h>
#define DIMENSION 256 
#define hmwt 159



void main()
{
    uint32_t index = 0, div = 0, remain = 0;
    uint32_t modulo[DIMENSION-hmwt+1][2];
    uint32_t M = 0xffff;

    for (int i = 0; i < DIMENSION-hmwt+1; i++){
        modulo[i][0] = i; 
        modulo[i][1] = 0; 
    }


    for (index = 0; index <= M; index++) {
        uint32_t deg = index;
        remain = M / (DIMENSION - hmwt + 1); //scaling factor 2**32 - 1 ---> d - hw + 1
        div = M - remain * (DIMENSION - hmwt + 1);
        div++;

        if (((M - deg) > div)) { 
            deg = deg / remain;   //Bring the deg 32-bit integer into a smaller domain d-hw + 1
            modulo[deg][1] = modulo[deg][1] + 1;
            printf("\n deg2 = %d", deg);
        }
        //printf("\n\n");
    }

    for (int i = 0; i < DIMENSION-hmwt+1; i++)
        printf("\n %d, %d", modulo[i][0], modulo[i][1]);
    printf("\n");


   
}
```

**Comment by she-cryptolab** [comment]
Hello, thank you for your interest in our implementation and sorry for delayed reply.
As you mentioned, there was an issue in the `hwt.c` of previous version 3.0. The `hwt.c` has now been updated with a different shuffling-based method. Please refer to the updated version.
